name: Publish Package to npmjs

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sbs-computing-js
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      
      - run: npm install
      - run: npm run build
      
      # Auto version management
      - name: Auto version management
        run: |
          # Get the last commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)
          
          # Determine version bump based on commit message
          if [[ $COMMIT_MSG == *"BREAKING CHANGE"* ]]; then
            npm version major --no-git-tag-version
          elif [[ $COMMIT_MSG == *"feat:"* ]]; then
            npm version minor --no-git-tag-version
          else
            npm version patch --no-git-tag-version
          fi
          
          # Get the new version
          NEW_VERSION=$(node -p "require('./package.json').version")
          
          # Create git tag
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add package.json
          git commit -m "chore: bump version to ${NEW_VERSION}"
          git tag -a "v${NEW_VERSION}" -m "Release v${NEW_VERSION}"
          git push --follow-tags
      
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 